import Head from 'next/head'

export default function Helmet() {
  return (
    <Head>
      <title>UCL Simulator</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
